CREATE TABLE "inventory"."purchase_order" (
  "id" uuid NOT NULL,
  "supplier" uuid,
  "prepared_by" uuid,
  "approved_by" uuid,
  "reviewed_by" uuid,
  "sent_by" uuid,
  "sent_date" timestamp(6),
  "prepared_date" timestamp(6),
  "approved_date" timestamp(6),
  "reviewed_date" timestamp(6),
  "payment_terms" varchar COLLATE "pg_catalog"."default",
  "delivery_terms" varchar COLLATE "pg_catalog"."default",
  "remarks" varchar COLLATE "pg_catalog"."default",
  "status" varchar COLLATE "pg_catalog"."default",
  "po_number" numeric,
  "prepared_by_signature" bytea,
  "approved_by_2" uuid,
  "approved_by_2_date" timestamp(6),
  "approved_by_2_signature" bytea,
  "approved_by_3" uuid,
  "approved_by_3_signature" bytea,
  "approved_by_3_date" timestamp(6),
  "approved_by_4" uuid,
  "approved_by_4_signature" bytea,
  "approved_by_4_date" timestamp(6),
  "revision_number" int4,
  "revision_note" varchar COLLATE "pg_catalog"."default",
  "approved_by_position" varchar COLLATE "pg_catalog"."default",
  "approved_by_2_position" varchar COLLATE "pg_catalog"."default",
  "approved_by_3_position" varchar COLLATE "pg_catalog"."default",
  "approved_by_4_position" varchar COLLATE "pg_catalog"."default",
  "po_sent_to_supplier" bool,
  "po_sent_notes" varchar COLLATE "pg_catalog"."default",
  "last_revision_by" uuid,
  "last_revision_date" timestamp(6),
  "revision_by_history" varchar COLLATE "pg_catalog"."default",
  "eta_date" timestamp(6),
  "deleted" bool,
  "created_by" varchar(50) COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT now(),
  "last_modified_by" varchar(50) COLLATE "pg_catalog"."default",
  "last_modified_date" timestamp(6) DEFAULT now(),
  PRIMARY KEY ("id")
)
;

CREATE TABLE "inventory"."purchase_order_items" (
  "id" uuid NOT NULL,
  "item" uuid NOT NULL,
  "quantity" numeric DEFAULT 0,
  "unit_measure" varchar COLLATE "pg_catalog"."default",
  "received_quantity" numeric DEFAULT 0,
  "date_completed" timestamp(6),
  "purchase_order" uuid,
  "receiving_report" uuid,
  "supplier_last_price" numeric DEFAULT 0,
  "dqi_received" numeric DEFAULT 0,
  "deleted" bool,
  "created_by" varchar(50) COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT now(),
  "last_modified_by" varchar(50) COLLATE "pg_catalog"."default",
  "last_modified_date" timestamp(6) DEFAULT now(),
  PRIMARY KEY ("id")
)
;