create schema inventory;

create table inventory.items
(
  id                             uuid not null
    constraint items_pkey
      primary key,
  stock_code                     varchar,
  desc_short                     varchar(50),
  desc_long                      varchar,
  unit_measure                   varchar,
  minimum_level                  varchar,
  economic_order_qty             numeric,
  prepared_by                    uuid,
  prepared_date                  timestamp without time zone,
  active                         boolean      default true,
  pharmacy_item                  boolean,
  stock_classification           varchar,
  indication_code                numeric,
  brand                          varchar,
  generic_name                   varchar,
  is_medicine                    boolean      default false,
  indication_desc                varchar,
  medication_description         varchar,
  sku                            varchar,
  route                          varchar,
  package_name                   varchar,
  package_content_count          numeric,
  barcode                        varchar,
  purchasing_item                boolean      default false,
  divisible_on_consumption       boolean,
  dose                           numeric,
  dose_unit                      varchar,
  company                        varchar,
  s2_drug                        boolean,
  form                           varchar,
  vatable                        boolean,
  preparation                    varchar,
  distributor                    varchar,
  advocate                       varchar,
  category                       varchar,
  sub_category                   varchar,
  sub_sub_category               varchar,
  formulary_item                 boolean,
  fluid                          boolean,
  gas                            boolean,
  direct_asset                   boolean,
  consignor                      uuid,
  consignment_item               boolean,
  consignor_name                 varchar,
  comlogic_medicine_code         varchar,
  comlogic_medicine_generic_code varchar,
  created_by                     varchar(50),
  created_date                   timestamp(6) default CURRENT_TIMESTAMP,
  last_modified_by               varchar(50),
  last_modified_date             timestamp(6) default CURRENT_TIMESTAMP
);